### ISSUE TITLE
Improve library import/export model

### ISSUE THREAD

**Issue by l7ssha** [nyxx-discord/nyxx#217]
All libraries currently use `part of` syntax which is discouraged. We should use `export` syntax with `show` to expose only needed APIs.

More here: https://dart.dev/guides/libraries/create-library-packages#organizing-a-library-package

Since its going to be breaking change it needs to be scheduled for `3.0.0`

#### Additional tasks
 - Implement plugin system and rewrite child packages into that plugin
 - Allow hooking into and expose hooks for various process in nyxx (like cache creation)
 - Add more tests, especially unit tests

### TODO:
 - [x] rewrite to new import/export model
   - [x] nyxx
   - [x] nyxx_interactions 
   - [x] nyxx_lavalink
   - [x] nyxx_commander
   - [x] nyxx_extensions
 - [x] plugin system
   - [ ] Implement plugin system 
     - [x] basic plugin lifecycle
     - [x] allow hooking into various internal framework events 
   - [ ] move main libs to plugin system
 - [x] improve code coverage

**Comment by l7ssha** [comment]
Closing since implemented on `next` branch
